packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@types/node': ^22.13.5
  '@eslint/js': ^9.20.0
  '@paralleldrive/cuid2': ^2.2.2
  babel-plugin-react-compiler: ^19.0.0-beta-21e868a-20250216
  dotenv: ^16.4.7
  dotenv-cli: ^8.0.0
  eslint: ^9.20.0
  eslint-config-prettier: ^10.0.1
  eslint-plugin-import-x: ^4.6.1
  eslint-plugin-react: ^7.37.4
  eslint-plugin-react-compiler: ^19.0.0-beta-21e868a-20250216
  eslint-plugin-react-hooks: ^5.1.0
  eslint-plugin-turbo: ^2.3.4
  globals: ^16.0.0
  prettier: ^3.5.2
  rimraf: ^6.0.1
  turbo: ^2.4.2
  typescript: ^5.7.3
  typescript-eslint: ^8.24.0
  vitest: ^3.0.6
