/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/app/route'
import { Route as LoginIndexImport } from './routes/login.index'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as PublicIndexImport } from './routes/_public/index'
import { Route as AppWorkspaceRouteImport } from './routes/app/$workspace/route'
import { Route as AppWorkspaceIndexImport } from './routes/app/$workspace/index'
import { Route as AppWorkspaceSelectImport } from './routes/app/workspace/select'
import { Route as AppWorkspaceCreateImport } from './routes/app/workspace/create'

// Create/Update Routes

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const AppRouteRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)

const PublicIndexRoute = PublicIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)

const AppWorkspaceRouteRoute = AppWorkspaceRouteImport.update({
  id: '/$workspace',
  path: '/$workspace',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppWorkspaceIndexRoute = AppWorkspaceIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkspaceRouteRoute,
} as any)

const AppWorkspaceSelectRoute = AppWorkspaceSelectImport.update({
  id: '/workspace/select',
  path: '/workspace/select',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppWorkspaceCreateRoute = AppWorkspaceCreateImport.update({
  id: '/workspace/create',
  path: '/workspace/create',
  getParentRoute: () => AppRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/app/$workspace': {
      id: '/app/$workspace'
      path: '/$workspace'
      fullPath: '/app/$workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexImport
      parentRoute: typeof PublicImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/app/workspace/create': {
      id: '/app/workspace/create'
      path: '/workspace/create'
      fullPath: '/app/workspace/create'
      preLoaderRoute: typeof AppWorkspaceCreateImport
      parentRoute: typeof AppRouteImport
    }
    '/app/workspace/select': {
      id: '/app/workspace/select'
      path: '/workspace/select'
      fullPath: '/app/workspace/select'
      preLoaderRoute: typeof AppWorkspaceSelectImport
      parentRoute: typeof AppRouteImport
    }
    '/app/$workspace/': {
      id: '/app/$workspace/'
      path: '/'
      fullPath: '/app/$workspace/'
      preLoaderRoute: typeof AppWorkspaceIndexImport
      parentRoute: typeof AppWorkspaceRouteImport
    }
  }
}

// Create and export the route tree

interface AppWorkspaceRouteRouteChildren {
  AppWorkspaceIndexRoute: typeof AppWorkspaceIndexRoute
}

const AppWorkspaceRouteRouteChildren: AppWorkspaceRouteRouteChildren = {
  AppWorkspaceIndexRoute: AppWorkspaceIndexRoute,
}

const AppWorkspaceRouteRouteWithChildren =
  AppWorkspaceRouteRoute._addFileChildren(AppWorkspaceRouteRouteChildren)

interface AppRouteRouteChildren {
  AppWorkspaceRouteRoute: typeof AppWorkspaceRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppWorkspaceCreateRoute: typeof AppWorkspaceCreateRoute
  AppWorkspaceSelectRoute: typeof AppWorkspaceSelectRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppWorkspaceRouteRoute: AppWorkspaceRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppWorkspaceCreateRoute: AppWorkspaceCreateRoute,
  AppWorkspaceSelectRoute: AppWorkspaceSelectRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteRouteWithChildren
  '': typeof PublicRouteWithChildren
  '/app/$workspace': typeof AppWorkspaceRouteRouteWithChildren
  '/': typeof PublicIndexRoute
  '/app/': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/app/workspace/create': typeof AppWorkspaceCreateRoute
  '/app/workspace/select': typeof AppWorkspaceSelectRoute
  '/app/$workspace/': typeof AppWorkspaceIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/app': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/app/workspace/create': typeof AppWorkspaceCreateRoute
  '/app/workspace/select': typeof AppWorkspaceSelectRoute
  '/app/$workspace': typeof AppWorkspaceIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/app': typeof AppRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/app/$workspace': typeof AppWorkspaceRouteRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/app/workspace/create': typeof AppWorkspaceCreateRoute
  '/app/workspace/select': typeof AppWorkspaceSelectRoute
  '/app/$workspace/': typeof AppWorkspaceIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | ''
    | '/app/$workspace'
    | '/'
    | '/app/'
    | '/login'
    | '/app/workspace/create'
    | '/app/workspace/select'
    | '/app/$workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/workspace/create'
    | '/app/workspace/select'
    | '/app/$workspace'
  id:
    | '__root__'
    | '/app'
    | '/_public'
    | '/app/$workspace'
    | '/_public/'
    | '/app/'
    | '/login/'
    | '/app/workspace/create'
    | '/app/workspace/select'
    | '/app/$workspace/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/app",
        "/_public",
        "/login/"
      ]
    },
    "/app": {
      "filePath": "app/route.tsx",
      "children": [
        "/app/$workspace",
        "/app/",
        "/app/workspace/create",
        "/app/workspace/select"
      ]
    },
    "/_public": {
      "filePath": "_public.tsx",
      "children": [
        "/_public/"
      ]
    },
    "/app/$workspace": {
      "filePath": "app/$workspace/route.tsx",
      "parent": "/app",
      "children": [
        "/app/$workspace/"
      ]
    },
    "/_public/": {
      "filePath": "_public/index.tsx",
      "parent": "/_public"
    },
    "/app/": {
      "filePath": "app/index.tsx",
      "parent": "/app"
    },
    "/login/": {
      "filePath": "login.index.tsx"
    },
    "/app/workspace/create": {
      "filePath": "app/workspace/create.tsx",
      "parent": "/app"
    },
    "/app/workspace/select": {
      "filePath": "app/workspace/select.tsx",
      "parent": "/app"
    },
    "/app/$workspace/": {
      "filePath": "app/$workspace/index.tsx",
      "parent": "/app/$workspace"
    }
  }
}
ROUTE_MANIFEST_END */
